import Head from 'next/head'
import {react} from 'React'
import { useState } from 'react'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

function Test(){
    return <h1>Worked</h1>
}

function Top(){
    // Define a state variable and its setter function
    const [inputValue, setInputValue] = useState('');
    const [showValue, setShowValue] = useState(false);
    // Handle input change and update state
    const handleInputChange = (event) => {
        setInputValue(event.target.value);
    };

    const handleClick = () => {
        setShowValue(!showValue);
        //parseIP({this.state.inputValue})
    }

    function parseIP(){

    }

    return (
        <div>
            <label>IP Address
                <input
                    type="text"
                    value={inputValue}
                    onChange={handleInputChange}
                />
                <button onClick={handleClick}>Submit</button>
                {showValue && <Test />}
                </label>
        </div>
  );
}

export default function Home() {
    const [showValue, setShowValue] = useState(false);

    const handleClick = () => {
        setShowValue(!showValue);
    }

  return (
    <>
        <Head>
            <title>Learning React</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <button onClick={handleClick}>Diagnostics</button>
            { showValue && <Top /> }
        </main>
    </>
  )
}
