import Head from 'next/head'
import Image from 'next/image'
import {react} from 'React'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

function Square(){
    const date = fetch('https://api.apis.guru/v2/list.json')
    .then(res => {
        //console.log(res.json);
        return res.json(); // treat fetch response as a .json format and return to next promise
    }).then( data => {
        return data['1forge.com'].added;
        //console.log(data['1forge.com'].added);
    }).catch(error => console.log(error)); 

    return (
        <div>{date}</div>
    );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Learning React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello React</h1>
        <Square />


      
      </main>
    </>
  )
}
